### ISSUE TITLE
Pull from pypi instead?

### ISSUE THREAD

**Issue by ericdill** [conda-forge/python-avro-feedstock#4]
@mariusvniekerk it would seem that python-avro is [now available on pypi](https://pypi.python.org/pypi/avro). Should we update the feedstock to just pull from that? Also are cyavro and python-avro interchangeable?

**Comment by mariusvniekerk** [comment]
Python avro is a pure python implementation of arrow - - so it's a lot slower. 

Pulling from pip seems like a good idea

**Comment by ericdill** [comment]
> so it's a lot slower.

But it at least exists for win/osx, so we can use selectors plus careful try/excepts to make packages that currently use cyavro accessible on win/osx too by using python-avro, right?

> Pulling from pip seems like a good idea

K. Adding that to my backlog.

**Comment by mariusvniekerk** [comment]
Changed to pull from official apache archive
